[package]
name = "linear_algebra"
version = "0.1.0"
authors = ["Kexin Su <ke.xin.su@ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"